# Generated by Django 4.0.4 on 2022-05-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='nombre',
            new_name='anonimo',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='moneda',
        ),
    ]
