# Generated by Django 4.0.4 on 2022-05-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0003_alter_donacion_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='anonimo',
            field=models.BooleanField(),
        ),
    ]
